INSERT INTO tb_tareas (nombre_tarea, responsable, estado) VALUES
('Relaciones sobre POO', 'Ronald Jaime', 'FINALIZADO'),
('Consultas acerca de JOIN en MySQL', 'Dariel Soto', 'PENDIENTE'),
('Aprender fundamentos de Java', 'Carlos Pérez', 'FINALIZADO'),
('Repasar Programación Orientada a Objetos', 'María López', 'EN_PROCESO'),
('Crear proyecto Spring Boot', 'Luis Gómez', 'FINALIZADO'),
('Configurar JPA con MySQL', 'Ana Torres', 'PENDIENTE'),
('Diseñar entidad Tarea', 'Ronald Jaime', 'FINALIZADO'),
('Crear repositorio JPA', 'Dariel Soto', 'FINALIZADO'),
('Implementar capa Service', 'Carlos Pérez', 'EN_PROCESO'),
('Configurar JavaFX', 'María López', 'FINALIZADO'),
('Crear interfaz con Scene Builder', 'Luis Gómez', 'EN_PROCESO'),
('Conectar JavaFX con Spring', 'Ana Torres', 'PENDIENTE'),
('Mostrar tareas en TableView', 'Ronald Jaime', 'FINALIZADO'),
('Agregar botón Guardar', 'Dariel Soto', 'PENDIENTE'),
('Agregar botón Eliminar', 'Carlos Pérez', 'PENDIENTE'),
('Validar formulario de tareas', 'María López', 'EN_PROCESO'),
('Configurar logging con Logback', 'Luis Gómez', 'FINALIZADO'),
('Crear base de datos empresa_db', 'Ana Torres', 'FINALIZADO'),
('Probar aplicación con H2', 'Ronald Jaime', 'FINALIZADO'),
('Migrar base de datos a MySQL', 'Dariel Soto', 'PENDIENTE'),
('Implementar Flyway', 'Carlos Pérez', 'PENDIENTE'),
('Crear scripts V1 y V2', 'María López', 'PENDIENTE'),
('Optimizar consultas JPA', 'Luis Gómez', 'EN_PROCESO'),
('Pruebas unitarias del servicio', 'Ana Torres', 'PENDIENTE'),
('Documentar el proyecto', 'Ronald Jaime', 'EN_PROCESO'),
('Subir proyecto a GitHub', 'Dariel Soto', 'PENDIENTE'),
('Preparar presentación final', 'Carlos Pérez', 'PENDIENTE');
